apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-runner
  namespace: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-edit
  namespace: spark
rules:
- apiGroups: ["", "batch", "apps"]
  resources: ["pods", "pods/log", "services", "configmaps", "secrets", "jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-edit
  namespace: spark
subjects:
- kind: ServiceAccount
  name: spark-runner
  namespace: spark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-edit
